- name: Build and install YOLOv2 for Neural Compute SDK2
  hosts: all
  become: True
  tasks:
    - name: Update all debian packages
      apt:
        upgrade: dist
    - name: Install Git
      apt:
        name: git
        update_cache: yes
    - name: Install core python dependencies
      apt:
        name:
          - python-dev
          - libxml2-dev
          - libxslt-dev
    - name: Clone Neural Compute SDK2
      git:
        repo: 'https://github.com/movidius/ncsdk.git'
        update: no
        dest: /srv/ncsdk
    - name: Build Neural Compute SDK2
      make:
        chdir: /srv/ncsdk
        target: install
    - name: Clone YOLO version 2
      git:
        repo: 'https://github.com/duangenquan/YoloV2NCS'
        update: no
        dest: /srv/yolo_v2
    - name: Build YOLO version 2
      make:
        chdir: /srv/yolo_v2
