---
# First play
- name: Configure webservers with nginx
  hosts: webservers
  become: True # become root
  vars:
    nginx_cfg_file: /etc/nginx/sites-available/default
  tasks:
    - name: install nginx # optional, but a must
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/nginx.cfg dest={{ nginx_cfg_file }}

    - name: enable configuration
      file: >-
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
